### ISSUE TITLE
are there any ways to speed up the first api call speed? 

### ISSUE THREAD

**Issue by qiankunli** [FalkorDB/FalkorDB#882]
I am use page_node api to  to render the entire graph(webui)  from a falkordb graph, fetching the first page of data, the first request is slow (5 seconds), and subsequent requests are much faster. are there any ways to speed up the first api call speed? such as create index for create_time property？

cypher for page_node node api

```
match (n)
return n.id, n.properties as properties
order by n.create_time
skip $offset
limit  $page_size
```
falkordb pod resources 
```
    resources:
      limits:
        cpu: 750m
        ephemeral-storage: 2Gi
        memory: 1536Mi
      requests:
        cpu: 500m
        ephemeral-storage: 50Mi
        memory: 1Gi
```
