### ISSUE TITLE
Data persistence not working in Docker

### ISSUE THREAD

**Issue by JoonasC** [FalkorDB/FalkorDB#911]
I'm using docker compose, and my config looks like this:
```
services:
  redis:
    image: falkordb/falkordb:v4.4.1
    volumes:
      - redis_data:/data
    restart: no
    environment:
      PORT: 3001
      NEXTAUTH_URL: "http://127.0.0.1:3001"
    ports:
      - "6379:6379"
      - "3001:3001"
volumes:
  redis_data:
```
According to the documentation persistence should work with this setup: [https://docs.falkordb.com/operations/persistence.html](https://docs.falkordb.com/operations/persistence.html)
Nevertheless, when I stop my container using `docker compose stop`, data is not persisted
