### ISSUE TITLE
he memory footprint is large, but the actual memory usage is small

### ISSUE THREAD

**Issue by nicolechec** [FalkorDB/FalkorDB#978]
FalkorDB version 4.6.4. Redis version=7.2.4

redis is deployed in the k8s cluster. Pods start and OOM until the memory resource is 48Gi. After entering the container, you can see that the actual memory is small, as shown in the following figure.

Previously, the pod memory of 8c/16G resources created 13Gi data volume and 10 graphs. After deleting the data through the GRAPH.DELETE command, the actual memory was reduced, pod was restarted again and remained OOM until the resource was adjusted to 48Gi

```
        resources:
          limits:
            cpu: "4"
            ephemeral-storage: 5Gi
            memory: 48Gi
          requests:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 16Gi
```

```
I have no name!@falkordb-redis-master-0:/FalkorDB$ redis-cli INFO MEMORY | grep -E 'used_memory_human|mem_fragmentation_ratio'
used_memory_human:15.56M
mem_fragmentation_ratio:18.49


```

![Image](https://github.com/user-attachments/assets/35e35706-3c4a-465d-be8f-f49671a4da72)
